# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: 104.154.54.91 (MySQL 5.7.14-google-log)
# Database: genome
# Generation Time: 2017-11-04 22:35:59 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table projects
# ------------------------------------------------------------

DROP TABLE IF EXISTS `projects`;

CREATE TABLE `projects` (
  `project_id` varchar(255) NOT NULL,
  `center_name` varchar(255) DEFAULT NULL,
  `description` longtext,
  `eva_center_name` varchar(255) DEFAULT NULL,
  `source_type` varchar(255) DEFAULT NULL,
  `study_type` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `taxonomy_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  KEY `FKo329l8c3pudnalawhd5n81618` (`taxonomy_id`),
  CONSTRAINT `FKo329l8c3pudnalawhd5n81618` FOREIGN KEY (`taxonomy_id`) REFERENCES `taxonomies` (`taxonomy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `projects` WRITE;
/*!40000 ALTER TABLE `projects` DISABLE KEYS */;

INSERT INTO `projects` (`project_id`, `center_name`, `description`, `eva_center_name`, `source_type`, `study_type`, `title`, `taxonomy_id`)
VALUES
	('abcc','hhkjjd',';laks;kf',';jnfdu','pislk','ajjk','ttest',4081),
	('PRJEB10956','University of Michigan Medical School','Targetted confirmatory sequencing of heterogenous variants detected by exome sequencing of spatially disparate areas from six rectal tumors',NULL,'Germline','Case Set','Intra-tumor Genetic Heterogeneity in Rectal Cancer',9606),
	('PRJEB10964','International Center for Tropical Agriculture (CIAT)','Whole genome sequencing and bioinformatic analysis of 104 rice cultivars including 54 elite lines from North America and Latin America',NULL,'Germline','Control Set','Whole genome sequencing of elite rice cultivars as a comprehensive information resource for marker assisted selection',4530),
	('PRJEB11471','Wellcome Trust Sanger Institute','SNP and INDEL calls from version 5 of the Mouse Genome Project at the Wellcome Trust Sanger Institute. Specifically, this project describes the variants of 36 mouse strains aligned against the reference mouse genome sequence GRCm38.',NULL,'Germline','Control Set','Sanger Institute Mouse Genomes Project v5',10088),
	('PRJEB11745','The Wellcome Trust Sanger Institute','The HipSci project brings together diverse constituents in genomics, proteomics, cell biology and clinical genetics to create a UK national iPS cell resource and use it to carry out cellular genetic studies.  In this sub-study we performed imputed whole exome sequencing using Agilent whole exome pulldown method on iPS cells generated from skin biopsies from healthy volunteers.',NULL,'Germline','Control Set','HipSci imputed whole exome sequencing data for healthy volunteers',9606),
	('PRJEB11746','The Wellcome Trust Sanger Institute','The HipSci project brings together diverse constituents in genomics, proteomics, cell biology and clinical genetics to create a UK national iPS cell resource and use it to carry out cellular genetic studies.  In this sub-study we performed whole exome sequencing using Agilent whole exome pulldown method on iPS cells generated from skin biopsies from healthy volunteers.',NULL,'Germline','Control Set','HipSci whole exome sequencing data for healthy volunteers',9606),
	('PRJEB11749','Wellcome Trust Sanger Institute','The HipSci project brings together diverse constituents in genomics, proteomics, cell biology and clinical genetics to create a UK national iPS cell resource and use it to carry out cellular genetic studies. In this sub-study we performed imputed Genotyping analysis using the Infinium HumanExome BeadChip on iPS cells generated from skin biopsies from healthy volunteers.',NULL,'Germline','Control Set','HipSci imputed genotyping array data for healthy volunteers',9606),
	('PRJEB11750','Wellcome Trust Sanger Institute','The HipSci project brings together diverse constituents in genomics, proteomics, cell biology and clinical genetics to create a UK national iPS cell resource and use it to carry out cellular genetic studies. In this sub-study we performed Genotyping analysis using the Infinium HumanExome BeadChip on iPS cells generated from skin biopsies from healthy volunteers.',NULL,'Germline','Control Set','HipSci genotyping array data for healthy volunteers',9606),
	('PRJEB11984','QIMR','Somatic mutations were identified in the QIMR Berghofer melanoma cell line collection using exome sequencing and comparing with matched germline',NULL,'Germline','Case Control','Somatic Mutations in QIMR Berghofer Melanoma Cell Line Collection Identified using Exome sequencing',9606),
	('PRJEB12769','IPMB, Academia Sinica','To study breeding and domestication trace of Taiwan',NULL,'Germline','Control Set','Diversity of Taiwan rice varieties',4530),
	('PRJEB12770','IPMB, Academia Sinica','For inspecting the level of the somatic variation from tissue culture and transformation, there were eight treatments applied on rice. The variety is Tainung67 (TNG67), which widely used in genomic study in Taiwan and with a large poplation T-DNA insertional lines, the Taiwan Rice Insertional Mutagenesis (TRIM).',NULL,'Germline','Control Set','Study the somatic variant due to tissue culture and transformation',4530),
	('PRJEB12771','IPMB, Academia Sinica','There were two diversed phenotype in one T-DNA insertional line. The project is about to investigate which gene or any factor cause such diversity via genomic tools.',NULL,'Germline','Control Set','One TRIM line, two diversed phenotype',39947),
	('PRJEB13080','Broad Institute','Anopheles stephensi subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles stephensi samples.',30069),
	('PRJEB13081','Broad Institute','Anopheles sinensis subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles sinensis samples.',74873),
	('PRJEB13082','Broad Institute','Anopheles quadriannulatus subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles quadriannulatus samples.',34691),
	('PRJEB13083','Broad Institute','Anopheles minimus subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles minimus samples.',112268),
	('PRJEB13084','Broad Institute','Anopheles merus subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles merus samples.',30066),
	('PRJEB13085','Broad Institute','Anopheles melas subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms. This subsection of the project contains data for Anopheles arabiensis.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles melas samples.',34690),
	('PRJEB13086','Broad Institute','Anopheles funestus subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles funestus samples.',62324),
	('PRJEB13087','Broad Institute','Anopheles farauti subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles farauti samples.',69004),
	('PRJEB13088','Broad Institute','Anopheles epiroticus subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles epiroticus samples.',199890),
	('PRJEB13089','Broad Institute','Anopheles culicifacies subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles culicifacies samples.',139723),
	('PRJEB13090','Broad Institute','Anopheles arabiensis subset of project sequencing 16 anopheline vector genomes to complement and facilitate comparative analysis with the three other sequenced anophelines, Anopheles gambiae PEST, M and S forms.',NULL,'Germline','Control Set','Highly evolvable malaria vectors: The genomes of 16 Anopheles mosquitoes. Anopheles arabiensis samples.',7173),
	('PRJEB13516','Oregon State University','Sequence reads from IR29, a salt-sensitive variety, were aligned to the reference Japonica genome to the identify single nucleotide polymorphisms',NULL,'Germline','Control Set','Transcriptome characterization and gene expression analyses of salt-tolerant and salt-sensitive varieties of IR29 Oryza sativa following exposure to salinity stress',4530),
	('PRJEB13517','Oregon State University','Sequence reads from Pokkali, a salt-sensitive variety, were aligned to the reference Japonica genome to the identify single nucleotide polymorphisms',NULL,'Germline','Control Set','Transcriptome characterization and gene expression analyses of salt-tolerant and salt-sensitive varieties of Pokkali Oryza sativa following exposure to salinity stress',4530),
	('PRJEB13618','International Rice Research Institute (IRRI)','The 3000 Rice Genome Project is an international effort to sequence the genomes of 3,024 rice varieties from 89 countries. The project contains the variant calls of 3000 samples against the Nipponbare reference genome sequence. This data is available for anyone to use under the terms of the Toronto Statement.',NULL,'Germline','Control Set','The 3,000 rice genomes project',4530),
	('PRJEB13625','Wellcome Trust Sanger Institute','Whole genome sequences of S. mansoni and S. rodhaini aligned to S. masoni v5.2 reference. Samples collected from Africa and Carribean to faciliate coalescence modelling of population history',NULL,'Germline','Control Set','Whole genome resequencing of the human parasite Schistosoma mansoni reveals population history and effects of selection',6183),
	('PRJEB14018','CRUK CAMBRIDGE RESEARCH INSTITUTE','Esophageal Adenocarcinoma (EAC) is highly mutated and molecularly heterogeneous. The number of cell lines available for study is limited and their genome has been only partially characterized. The availability of an accurate annotation of their mutational landscape is crucial for accurate experimental design and correct interpretation of genotype-phenotype findings. We performed high coverage, paired end whole genome sequencing on eight EAC cell lines—ESO26, ESO51, FLO-1, JH-EsoAd1, OACM5.1 C, OACP4 C, OE33, SK-GT-4—all verified against original patient material, and one esophageal high grade dysplasia cell line, CP-D. We have made available the aligned sequence data and report single nucleotide variants (SNVs), small insertions and deletions (indels), and copy number alterations, identified by comparison with the human reference genome and known single nucleotide polymorphisms (SNPs). We compare these putative mutations to mutations found in primary tissue EAC samples, to inform the use of these cell lines as a model of EAC.',NULL,'Germline','Case Control','Whole Genome Sequencing of eight EAC cell lines—ESO26, ESO51, FLO-1, JH-EsoAd1, OACM5.1 C, OACP4 C, OE33, SK-GT-4—and one esophageal high grade dysplasia cell line, CP-D.',9606),
	('PRJEB14378','International Rice Research Institute','We initiated the OryzaSNP project (www.OryzaSNP.org) to discover genetic variation within 20 rice varieties and landraces. Most varieties belong to the 2 main groups, indica and japonica, including tropical and temperate japonica, whereas others represent the aus, deep water, and aromatic rice groups. Here, we describe the discovery of high-quality, nonredundant SNPs distributed across the entire genomes of the OryzaSNPset.',NULL,'Germline','Control Set','Genomewide SNP variation reveals relationships among landraces and modern varieties of rice',4530),
	('PRJEB14385','Cornell University','In this study, we utilize a novel 1,536 SNP panel genotyped across 395 diverse accessions of O. sativa to study genome-wide patterns of polymorphism, to characterize population structure, and to infer the introgression history of domesticated Asian rice. ',NULL,'Germline','Control Set','Genomic diversity and introgression in O. sativa reveal the impact of domestication and breeding on the rice genome',4530),
	('PRJEB14684','ISGC','Raw variant discovery using multiple sheep breeds - Run1: Fastq files were aligned to Ovis aries reference genome version 3.1 using bwa mem. Duplicates were removed using Samtools rmdup. Local realignment around indels was performed using GATK tools RealignerTargetCreator and IndelRealigner. Variant calling on resulting BAM files was conducted independently using both Samtools mpileup and GATK Unified Genotyper. A union set of the Samtools and GATK called variants was produced using GATK CombineVariants to produce the final VCF files. (Software: bwa-0.7.12,GATK-3.4-46,samtools-1.2+htslib-1.2.1)',NULL,'Germline','Control Set','Raw variant calls from the Sheep genomes project - Run1',9940),
	('PRJEB14685','ISGC','High quality variant discovery using multiple sheep breeds - Run1: Fastq files were aligned to Ovis aries reference genome version 3.1 using bwa mem. Duplicates were removed using Samtools rmdup. Local realignment around indels was performed using GATK tools RealignerTargetCreator and IndelRealigner. Variant calling on resulting BAM files was conducted independently using both Samtools mpileup and GATK Unified Genotyper. Filters were applied to each of the Samtools and GATK produced VCF files to remove lower quality variants. These filters included remove variants with 2 or more alleles, remove variants never observed on forward or reverse strands, remove variants with overall quality less than phred score 20, remove variants with mapping quality less than phred score 30, remove variants with minimum depth less than 10 across all samples, remove variants with the same base pair position, remove lower quality indel when indels closer than 10 base pairs, remove lower quality variant where variants closer than 3 base pairs, remove SNP within 5bp of an indel. GATK CombineVariants was used to produce a union set of the filtered variants. An intersect set containing those variants concordant between Samtools and GATK predictions was extracted from this union set using GATK SelectVariants to produce the final VCF files. (Software: bwa-0.7.12,GATK-3.4-46,samtools-1.2+htslib-1.2.1)',NULL,'Germline','Control Set','High quality variant calls from the Sheep genomes project - Run1',9940),
	('PRJEB14713','Wenzhou Medical University','Identification of genomic variants from whole-genome sequencing dataset of 32 Chinese trios with autism, including de novo mutations (DNMs), inherited variants, copy number variants (CNVs) and genomic structural variants (SVs).',NULL,'Germline','Control Set','Whole-genome sequencing expands the mutational spectrum of autism with novel genes, causative CNVs and chromosomal rearrangements',9606),
	('PRJEB14878','Unit of Animal Genomics, University of Liege, Belgium','Sex differences in global recombination and genetics of recombination in cattle',NULL,'Germline','Control Set','Recombination in cattle',9913),
	('PRJEB14879','Unit of Animal Genomics, University of Liege, Belgium','Sex differences in global recombination and genetics of recombination in cattle - imputed variants',NULL,'Germline','Control Set','Recombination in cattle - imputed',9913),
	('PRJEB15197','deCODE Genetics','Sequence variants identified in deCODE\'s whole-genome sequencing of 15,220 Icelanders',NULL,'Germline','Control Set','deCODE Genetics whole-genome sequencing variants 2',9606),
	('PRJEB15198','deCODE Genetics','de novo mutations identified in deCODE\'s whole-genome sequencing of 15,220 Icelanders',NULL,'Germline','Control Set','deCODE Genetics whole-genome de novo variants',9606),
	('PRJEB15384','Illumina','Illumina Platinum Genomes calls for NA12877 and NA12878 against GRCh38',NULL,'Germline','Control Set','Illumina Platinum Genomes calls for NA12877 and NA12878 against GRCh38',9606),
	('PRJEB15385','Illumina','Illumina Platinum Genomes calls for NA12877 and NA12878 against GRCh37',NULL,'Germline','Control Set','Illumina Platinum Genomes calls for NA12877 and NA12878 against GRCh37',9606),
	('PRJEB15642','Curtin University','We undertook the first whole genome variant analysis of the Djallonke and the Sahelian sheep breeds of Ghana. WGS from five individuals each of Djallonke and Sahelian sheep was sequenced on an Ion Proton. A total of approximately 404 million (97%) and 343 million (97%) sequence reads from the Djallonke and Sahelian genomes respectively were successfully mapped to the sheep reference genome  Oar_3.1/oviAri3. The mapped samples for each breed were then pooled. Variants were called/genotyped using a pipeline modified from GATK best practices.',NULL,'Germline','Control Set','Molecular characterisation of Djallonke and Sahelian sheep breed genomes',9940),
	('PRJEB17529','UNIVERSITY COLLEGE LONDON','About PGP UK:Founded in 2013 by Stephan Beck, the United Kingdom Personal Genome Project is located at University College London.PGP UK is a member of the Global Network of Personal Genome Projects (PGP), a group of research studies creating freely available scientific resources that bring together genomic, environmental and human trait data donated by volunteers. Initiated by George Church at Harvard Medical School in 2005, the Personal Genome Project has pioneered ethical, legal, and technical aspects related to the creation of public resources involving highly identifiable data like human genomes.We believe sharing is good for science and society. Our project is dedicated to creating public resources that everyone can access. Privacy, confidentiality and anonymity are impossible to guarantee in a context like this research study where public sharing of genetic data is an explicit goal. Therefore, our project collaborates with participants who are fully aware of the implications and privacy concerns of making their data public. Volunteering is not for everyone, but the participants who join make a valuable and lasting contribution to science.We respect the people behind the data, and we aim to maintain strong relationships with participants. We want to collaborate on tracking health and other traits as they unfold over time. We also want to better understand the benefits and risks related to accessing and sharing personal genomes and other types of data.The genome is just a part of the story: genes interact with the environment to form traits. Participants may choose to contribute other public data to build public records of their health and traits. We also try to connect participants with research, education, and citizen science projects that are connected to personal genome data',NULL,'Germline','Control Set','Personal Genome Project - United Kingdom',9606),
	('PRJEB18671','CIAT, UCDavis, Universidad de los Andes','Whole genome sequencing and bioinformatic analysis of 29 cultivars of common bean (Phaseolus vulgaris), nine pools and 2 cultivated relatives of P. coccineus and P. acutifolius',NULL,'Germline','Control Set','Sequencing of common bean genotypes provides comprehensive resources for genetic studies and molecular breeding',3885),
	('PRJEB19387','University of León','Archive with all the variants detected within the sheep milk somatic cell transcriptome. Transcriptome sequencing (RNA-seq) was performed on total RNA extracted from milk somatic cells from ewes on days 10, 50, 120 and 150 after lambing. The experiment was performed in 4 Spanish Churra and 4 Assaf sheep, which differ in their milk production traits. The project Coordinator is Juan José Arranz from University of León, Spain.',NULL,'Germline','Control Set','Archive of Transcriptomic Variants within the Sheep Milk Somatic Cells',9940),
	('PRJEB19523','SGI','85 panel samples from the Samsung Medical Centre',NULL,'Germline','Control Set','Samsung Medical Centre: 85 panel samples',9606),
	('PRJEB19524','SGI','36 familial exomes from the Samsung Medical Centre',NULL,'Germline','Control Set','Samsung Medical Centre: 36 familal exomes',9606),
	('PRJEB19794','Technical University of Denmark','Sequencing of Danish parent-offspring trios to determine genomic variation within the Danish population. Phase II comprises of 50 trios sequenced to 80X using Illumina with libraries of insert sizes from 180bp-20kb.',NULL,'Germline','Control Set','The Danish reference pan genome phase II',9606),
	('PRJEB20009','Iowa State University','Cattle genetic variation data from 16 animals across 28 samples',NULL,'Germline','Control Set','Cattle genetic variation data from 16 animals across 28 samples',9913),
	('PRJEB20726','EMC','All variants detected by whole exome sequencing of 2628 Dutch healthy elderly individuals',NULL,'Germline','Control Set','Rotterdam Study Exome Sequencing Freeze 2',9606),
	('PRJEB20817','Center for Genomic Medicine, Massachusetts General Hospital','Genotypes of 21 common SNPs in Huntington\'s disease subjects',NULL,'Germline','Control Set','Haplotype-based stratification of Huntington\'s disease',9606),
	('PRJEB20820','BGI-Shenzhen','We performed whole genome sequencing at high depth (~80X) of 90 unrelated individuals of Chinese ancestry, collected from the 1000 Genome Project samples, including 45 North Han Chinese and 45 South Han Chinese samples. 83 of these 90 have been sequenced by the 1000 Genomes Project. We have identified 12,568,804 single nucleotide polymorphisms and 2,074,210 short InDels from these 90 samples.',NULL,'Germline','Control Set','Deep whole-genome sequencing of 90 Han Chinese genomes',9606),
	('PRJEB21300','deCODE genetics/Amgen Inc.','deCODE Release 2: whole-genome de novo variants from the proband from 1548 Icelandic trios',NULL,'Germline','Control Set','deCODE Release 2: whole-genome de novo variants from the proband from 1548 Icelandic trios',9606),
	('PRJEB21794','OMIA','This project describes two likely causal variants (LCVs) for bulldog dwarfism in Dexter cattle',NULL,'Germline','Control Set','OMIA LCV: Bulldog dwarfism in Dexter cattle',9913),
	('PRJEB22189','Norsvin SA','Variant detection in RNA-seq data from boars with high/low sperm DFI',NULL,'Germline','Control Set','Boar sperm DNA fragmentation',9823),
	('PRJEB22261','Key Laboratory of Healthy Mariculture for the East China Sea, Jimei University','The SNP and indel (length less than 50bp) data from large yellow croaker (Larimichthys crocea)',NULL,'Germline','Control Set','genetic variantion data for LYC',215358),
	('PRJEB22799','Wellcome Trust Sanger Institute','The process of producing the GRC zebrafish assembly included the high-quality sequencing and finishing of clones representing alternate haplotypes to corresponding regions in the current primary assembly. This project reports the variation between those alternate haplotype clones and the primary assembly.',NULL,'Germline','Control Set','GRCz11 Alternate Haplotype Clone Variants',7955),
	('PRJEB22833','Rat Genome Database','Mammary cancer; congenic rat strain characterization.',NULL,'Germline','Control Set','Shull laboratory snps',10116),
	('PRJEB22866','Functional genome of Chinese native horse.','To improve the technical standard and explore horse functional genome.',NULL,'Germline','Control Set','Public Science and Technology Research Funds Projects of Agriculture',9796),
	('PRJEB22988','Gregor Mendel Institute','Callset of filtered imputed and phased biallelic SNP genotypes of 163 vervet monkeys (genus Chlorocebus) from several African and Caribbean countries as described in Svardal et al. Nature Genetics 2017. Sample information can be found in Data S1 of Svardal et al. 2017.',NULL,'Germline','Control Set','Imputed phased whole genome SNP variants for 163 vervet monkeys',60711),
	('PRJEB22989','Gregor Mendel Institute','Callset of filtered SNP and indel genotypes of 163 vervet monkeys (genus Chlorocebus) from several African and Caribbean countries as described in Svardal et al. Nature Genetics 2017. Sample information can be found in Data S1 of the publication above. There is one VCF file per chromosome. Genotypes are not imputed and unphased. There is missing data. Note that there also is a imputed and phased dataset of biallelic SNPs available as a separate submission which might be more useful for many applications. Fixed differences between vervet and macaque have been added to the VCFs (mainly the sites with AC=0 and AF=0.000) so that variant effects are also annotated for divergent sites between vervet and macaque. Where available, the macaque state is given by the INFO tag \'AA\'. Variant effects have been annotated. Please refer to the methods section of the article cited above for a full description of the data. &lt;hannes.svardal@gmail.com&gt;',NULL,'Germline','Control Set','Effect annotated whole genome variants for 163 vervet monkeys (SNPs, Indels, and macaque fixed differences)',60711),
	('PRJEB23068','INIA','RNA-Seq analysis carried out in three different backcrosses based on Iberian breed with Landrace, Pietrain and Duroc breeds',NULL,'Germline','Control Set','RNA-Seq Analysis',9823),
	('PRJEB2733','SC','S.pombe is the \"other yeast\" genetic model system.  All 107 known wild isolates have been collected  around the world.  14 have already been sequenced.  The aim of the study is to sequence 96 samples (three overlapping with the previously sequenced 14) to generate a genetic diversity resource for S.pombe comparable to that available for  S.cerevisiae. This data is part of a pre-publication release. For information on the proper use of pre-publication data shared by the Wellcome Trust Sanger Institute (including details of any publication moratoria), please see http://www.sanger.ac.uk/datasharing/',NULL,'Germline','Control Set','Schizosaccharomyces pombe genetic diversity',4896),
	('PRJEB3025','IPK-Gatersleben','Variation data is shown from four cultivar (Barke, Bowman, Igri, Haruna Nijo) and a wild barley (H. spontaneum).','Leibniz Institute of Plant Genetics and Crop Plant Research (IPK), D-06466 Seeland OT Gatersleben, Germany; Leibniz Institute of Age Research- Fritz Lipmann Institute (FLI), D-07745 Jena, Germany','Germline','Control Set','Whole genome shotgun survey sequencing of Barley cv. Igri for de novo assembly of gene-space',112509),
	('PRJEB3027','IPK-Gatersleben','Barley (Hordeum vulgare L.) is amongst the oldest domesticated crop plants and remains one of the world\'s most important crop species. It is diploid with a haploid genome of 5.1 gigabases (Gb), twice the size of those of human and maize, and closely related to the most widely grown crop, hexaploid wheat. To meet global demand for food, feed and fibre, it is commonly agreed that reference genome sequences of our crop plants are urgently required to enable genome-assisted crop improvement. In the framework of the The International Barley Genome Sequencing Consortium (IBSC) we present here the whole genome shotgun rawdata of different barley cultivars and genotypes to build a physical ordered genetic and functional sequence resource.','Leibniz Institute of Plant Genetics and Crop Plant Research (IPK), D-06466 Seeland OT Gatersleben, Germany; Leibniz Institute of Age Research- Fritz Lipmann Institute (FLI), D-07745 Jena, Germany','Germline','Control Set','Whole genome shotgun survey sequencing  of Barley cv. Morex for de novo assembly of gene-space',112509),
	('PRJEB3040','IPK-Gatersleben','Variation data is shown from four cultivar (Barke, Bowman, Igri, Haruna Nijo) and a wild barley (H. spontaneum).','Leibniz Institute of Plant Genetics and Crop Plant Research (IPK), D-06466 Seeland OT Gatersleben, Germany; Leibniz Institute of Age Research- Fritz Lipmann Institute (FLI), D-07745 Jena, Germany','Germline','Control Set','Whole genome shotgun survey sequencing of Barley cv. Bowman for de novo assembly of gene-space',112509),
	('PRJEB3041','IPK-Gatersleben','Variation data is shown from four cultivar (Barke, Bowman, Igri, Haruna Nijo) and a wild barley (H. spontaneum).','Leibniz Institute of Plant Genetics and Crop Plant Research (IPK), D-06466 Seeland OT Gatersleben, Germany; Leibniz Institute of Age Research- Fritz Lipmann Institute (FLI), D-07745 Jena, Germany','Germline','Control Set','Whole genome shotgun survey sequencing of Barley cv. Barke for de novo assembly of gene-space',112509),
	('PRJEB3042','IPK-Gatersleben','Variation data is shown from four cultivar (Barke, Bowman, Igri, Haruna Nijo) and a wild barley (H. spontaneum).','Leibniz Institute of Plant Genetics and Crop Plant Research (IPK), D-06466 Seeland OT Gatersleben, Germany; Leibniz Institute of Age Research- Fritz Lipmann Institute (FLI), D-07745 Jena, Germany','Germline','Control Set','Whole genome shotgun survey sequencing of Barley cv. Haruna Nijo for de novo assembly of gene-space',112509),
	('PRJEB4019','1000 Genomes Project','Variant discovery and individual genotypes for 1092 individuals from the 1000 Genomes Project Phase 1 data release. This accession is a snapshot, as of June 26, 2013, of directory ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/analysis_results/integrated_call_sets Individual level genotype information is contained in a separate .vcf file for each chromosome; the variant site information (first eight columns of .vcf format) is also collected in a single sites-only .vcf file. The .vcf version 4.1 file format is described at http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-41 Variant discovery and genotyping are based on both low coverage whole genome sequencing and deep coverage exon capture sequencing by the 1000 Genomes Project. The Phase 1 low coverage sequencing was done between 2008 and 2010 using Illumina (86.4%), AB SOLiD (13%) and Roche LS 454 (0.6%) sequencing technologies, with a raw sequencing data freeze date of Nov 23, 2010. Exon capture sequencing was done in 2010 and early 2011, using either the NimbleGen SeqCap_EZ_Exome_v2 or Agilent SureSelect_All_Exon_V2 exome capture reagents, with a freeze date of May 21, 2011. After filtering, variant site discovery yields a total of 38 M SNPs, 1.4 M short indels and 14 K large deletions (longer than 50 bp). The short indels and large deletions in particular have been stringently filtered in order to achieve the project goal of not more than 5% false discovery rate. All coordinates are relative to the GRCh37 human genome reference sequence. Site discovery and genotyping for SNPs are based on both low coverage and exome capture sequence data; for short indels, only low coverage data, and for large deletions, only the 946 individuals with Illumina low coverage sequence data are used. As a final step, statistical genotype imputation using the linkage disequilibrium between nearby sites refines the individual genotypes and merges information from all three variant types. Details of data generation and processing for this data set are given in supplementary material to the 1000 Genomes Phase 1 paper: 1000 Genomes Project Consortium, Goncalo R. Abecasis, Adam Auton, Lisa D. Brooks, Mark A. DePristo, Richard M. Durbin, Robert E. Handsaker, Hyun M. Kang, Gabor T. Marth, Gil A. McVean (2012). An integrated map of genetic variation for 1,092 human genomes. Nature, v.491, n.7422, pp.56-65, Nov 1, 2012, PMID: 23128226, doi: 10.1038/nature11632. Further details and supporting data are in other subdirectories under: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1','The 1000 Genomes Project Consortium','Germline','Control Set','1000 Genomes Phase 1 Analysis 12',9606),
	('PRJEB4163','SC','The genome sequences of Strongyloides ratti, S. stercoralis, S. papillosus and S. venezuelensis are providing a clear view of genome diversity within this genus. These species include one human parasite, one parasite of veterinary relevance and two species from rodents, used as laboratory models. We now want to better understand this within-genus diversity, by also looking at the genome diversity with one species, specifically S. ratti. There are different isogenic lines of S. ratti available. (These other lines are recently wild, whereas the S. ratti line sequenced so far has a very long history of laboratory adaptation.) Further, phenotypic data from these lines show that they differ in important infection characteristics.  These isofemale lines of S. ratti differ in their fecundity (which, for a parasite is key to transmission potential), particularly in the presence of the host immune response (which, in general suppresses nematode reproduction). These line also differ in the extent to which they reproduce by sexual reproduction outside of the host (compared with the alternative, asexual reproduction). Analogously, this trait (sex vs. no sex) is also affected by the host immune response. Together, this means that these S. ratti lines differ in how they respond to the host immune response, which emphasies that this parasite\'s interaction with their host is dynamic both on short (i.e. within a worms lifetime) and long (i.e. evolutionary) term time scales. Exploring the genome diversity within this species will therefore begin to illuminate our understanding of these phenotypic differences.',NULL,'Germline','Control Set','Strongyloides ratti genetic diversity',34506),
	('PRJEB4395','Institut National de la Recherche Agronomique - France','Whole genome re-sequencing in tomato reveals variation associated with introgression and breeding events. Here we describe the whole-genome resequencing of eight tomato samples chosen to represent a large range of intra-specific variability and the identification and annotation of novel polymorphisms.Comparison of the sequences with the reference genome yielded more than 4 million single nucleotide polymorphisms (SNPs) and almost 128,000 InDels were detected.This study represents the first whole genome resequencing experiment in cultivated tomato.',NULL,'Germline','Control Set','Whole genome re-sequencing in tomato',4081),
	('PRJEB5439','University of Michigan and the Broad Institute','The goal of the NHLBI GO Exome Sequencing Project (ESP) is to discover novel genes and mechanisms contributing to heart, lung and blood disorders by pioneering the application of next-generation sequencing of the protein coding regions of the human genome across diverse, richly-phenotyped populations and to share these datasets and findings with the scientific community to extend and enrich the diagnosis, management and treatment of heart, lung and blood disorders.','University of Michigan; The Broad Institute','Germline','Aggregate','Exome Variant Server NHLBI Exome Sequencing Project',9606),
	('PRJEB5829','The University Medical Center Groningen, Leiden University Medical Center, Erasmus Medical Center, Vrije Universiteit Amsterdam, University Medical Centre Utrecht','GoNL: Genome of the Netherlands Release 5','The University Medical Center Groningen; Leiden University Medical Center; Erasmus Medical Center; Vrije Universiteit Amsterdam; University Medical Centre Utrecht','Germline','Control Set','Genome of the Netherlands Release 5',9606),
	('PRJEB5966','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) (Tax ID 9940) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','Sheep EVA Tax ID 9940',9940),
	('PRJEB5967','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) (Tax ID 9938) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','Sheep EVA Tax ID 9938',9938),
	('PRJEB5978','EBI','Variation site discovery and genotype calls in the genus Capra (goat) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options).',NULL,'Germline','Control Set','NextGen project variation for Capra aegagrus',9923),
	('PRJEB6024','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) (Tax ID 9940) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','Sheep EVA Tax ID 9940 update',9940),
	('PRJEB6025','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','NextGen project variation for Ovis aries',9940),
	('PRJEB6033','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) (Tax ID 9938) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','NextGen project variation for Ovis (sheep) (Tax ID 9938)',9938),
	('PRJEB6040','SC','The UK10K project proposes a series of complementary genetic approaches to find new low-frequency/rare variants contributing to disease phenotypes. These will be based on obtaining the genome-wide sequence of 4000 samples from the TwinsUK and ALSPAC cohorts (at 6x sequence coverage), and the exome sequence (protein-coding regions and related conserved sequence) of 6000 samples selected for extreme phenotypes. Our studies will focus primarily on cardiovascular-related quantitative traits, obesity and related metabolic traits, neurodevelopmental disorders and a limited number of extreme clinical phenotypes that will provide proof-of-concept for future familial trait sequencing. We will directly analyse quantitative traits in the cohorts and the selected traits in the extreme samples, and also use imputation down to 0.1% allele frequency to extend the analyses to further sample sets with genome wide genotype data. In each case we will investigate indels and larger structural variants as well as SNPs, and use statistical methods that combine rare variants in a locus or pathway as well as single-variant approaches. The TwinsUK samples will be part of the cohort study and will undergo whole genome sequencing. For further information with regard to this cohort please contact Brent Richards (brent.richards@kcl.ac.uk) or Nicole Soranzo (ns6@sanger.ac.uk).','Wellcome Trust Sanger Institute','Germline','Control Set','UK10K',9606),
	('PRJEB6041','University of Groningen, University Medical Center Groningen, Department of Genetics, Groningen, the Netherlands','Genetic variants called in individuals screened for heritable cardiomyopathies using the UMCG Cardio GenePanels',NULL,'Germline','Case Set','UMCG Cardio GenePanel screening',9606),
	('PRJEB6042','Center for Genomic Regulation - CRG (Barcelona), Institute of Human Genetics - Helmholtz Zentrum (Munich)','GEUVADIS: Genetic European Variation in Disease (http://www.geuvadis.org), is a European Medical Sequencing Consortium aiming at sharing capacity across Europe in high-throughput sequencing technology to explore genetic variation in health and disease. It is funded by the European Commission 7th framework program under the Coordination and Support Action scheme. It started on the 1st October 2010, and ends on 31st December 2013. The project Coordinator is Xavier Estivill from Center for Genomic Regulation, Barcelona.','Center for Genomic Regulation - CRG (Barcelona); Institute of Human Genetics - Helmholtz Zentrum (Munich)','Germline','Aggregate','GEUVADIS: Genetic European Variation in Disease',9606),
	('PRJEB6057','EBI','Variation site discovery and genotype calls in the genus Capra (goat) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options).',NULL,'Germline','Control Set','NextGen project variation for Capra hircus',9925),
	('PRJEB6119','EBI','Variation site discovery and genotype calls in the genus Bos (cattle) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options).',NULL,'Germline','Control Set','NextGen project variation for Bos taurus',9913),
	('PRJEB629','IPK-Gatersleben','Hordeum vulgare subsp. vulgare',NULL,'Germline','Control Set','Sequencing of five barley cultivars.',112509),
	('PRJEB6495','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','NextGen project variation for Ovis orientalis',469796),
	('PRJEB6506','EBI','Variation site discovery and genotype calls in the genus Ovis vignei (sheep) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options)',NULL,'Germline','Control Set','NextGen project variation for Ovis vignei (sheep)',59896),
	('PRJEB6902','Complete Genomics','A list of all of the variants in the set of 69 Complete Genomics genomes, generated using the CGA Tools (v1.5) listvariants command',NULL,'Germline','Control Set','Complete Genomics 69 Genomes',9606),
	('PRJEB6911','Wellcome Trust Sanger Institute','SNP and INDEL calls from version 3 of the Mouse Genome Project at the Wellcome Trust Sanger Institute. Specifically, this project describes the variants of 18 mouse strains (129P2, 129S1, 129S5, A/J, AKR/J, BALB/cJ, C3H/HeJ, C57BL/6NJ, CAST/EiJ, CBA/J, DBA/2J, FVB/NJ, LPJ, NOD/ShiLtJ, NZOHILtJ, PWK/PhJ, SPRET/EiJ, WSB/EiJ) called against the reference mouse genome sequence GRCm38.',NULL,'Germline','Control Set','Sanger Institute Mouse Genomes Project v3',10088),
	('PRJEB6930','EBI','This submission contains variant sites and phased genotypes for all autosomes (excluding a 3Mbps region on chromosome 12 between 7M and 10M) derived from the 1000 Genomes Project phase3 sequence data. ~3400 unphased sites were removed from the submission while they are being investigated. The missing data on chromosome 12 are being patched up and will be submitted at a later time together with the sex chromosomes. This data set is based on 20130502 sequence freeze and alignments; which were collected from 2504 unrelated individuals from 26 populations. The analysis was run using only Illumina platform sequence and only considered sequence with read lengths of 70bp or greater.',NULL,'Germline','Control Set','1000 Genomes Project phase3 release V3+',9606),
	('PRJEB7061','EBI','Variation site discovery and genotype calls in the genus Bos (cattle) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options).',NULL,'Germline','Control Set','NextGen project variation for Bos taurus x Bos indicus',30523),
	('PRJEB7217','SC','The UK10K project proposes a series of complementary genetic approaches to find new low-frequency/rare variants contributing to disease phenotypes. These will be based on obtaining the genome-wide sequence of 4000 samples from the Department of Twin Research and Genetic Epidemiology (TwinsUK) and Avon Longitudinal Study of Parents and Children (ALSPAC) cohorts (at 6x sequence coverage), and the exome sequence (protein-coding regions and related conserved sequence) of 6000 samples selected for extreme phenotypes. This project describes the variants identified from the ALSPAC study. For further information with regard to this cohort please contact Brent Richards (brent.richards@kcl.ac.uk) or Nicole Soranzo (ns6@sanger.ac.uk).','Wellcome Trust Sanger Institute','Germline','Control Set','UK10K Avon Longitudinal Study of Parents and Children (ALSPAC) Variants',9606),
	('PRJEB7218','SC','The UK10K project proposes a series of complementary genetic approaches to find new low-frequency/rare variants contributing to disease phenotypes. These will be based on obtaining the genome-wide sequence of 4000 samples from the Department of Twin Research and Genetic Epidemiology (TwinsUK) and Avon Longitudinal Study of Parents and Children (ALSPAC) cohorts (at 6x sequence coverage), and the exome sequence (protein-coding regions and related conserved sequence) of 6000 samples selected for extreme phenotypes. This project describes the variants identified from the TwinsUK study. For further information with regard to this cohort please contact Brent Richards (brent.richards@kcl.ac.uk) or Nicole Soranzo (ns6@sanger.ac.uk).','Wellcome Trust Sanger Institute','Germline','Control Set','UK10K The Department of Twin Research and Genetic Epidemiology (TwinsUK) Variants',9606),
	('PRJEB7378','EBI','Variation site discovery and genotype calls in the genus Ovis (sheep) by the NEXTGEN project (Next generation methods to preserve farm animal diversity by optimizing present and future breeding options).',NULL,'Germline','Control Set','NextGen project variations for Ovis (sheep)',9935),
	('PRJEB7723','Cornell University','This project improves our understanding of the genetic architecture of complex traits in maize and its wild relative, teosinte. Maize has a combination of life history, economic and societal value, and genetic tools that make it uniquely suited to studying genetic architecture. Additionally, the ability of molecular and population genetic polymorphism descriptors to aid identifcation of functional rare alleles is also a key outcome of this project as is the prediction of phenotype from genotype in diverse maize cultivars.',NULL,'Germline','Control Set','Biology of Rare Alleles in Maize',4577),
	('PRJEB7894','Liverpool School of Tropical Medicine; Address: Pembroke Place, Liverpool, L35QA','Genotyping of Anopheles gambia M and S form mosquitoes from African populations collected at Yaounde (Cameroon), Dodow (Ghana), Tororo (Uganda) and Antula (Guinea-Bissau).',NULL,'Germline','Control Set','Genetic divergence between Anopheles gambiae M and S forms',7165),
	('PRJEB7895','Institute for Molecular Medicine Finland','The FINRISK cohorts comprise the respondents of representative, cross-sectional population surveys that are carried out every 5 years since 1972, to assess the risk factors of chronic diseases (e.g. CVD, diabetes, obesity, cancer) and health behavior in the working age population, in 3-5 large study areas of Finland. DNA samples were collected in the following survey years: 1987, 1992, 1997, 2002, 2007, and 2012.',NULL,'Germline','Aggregate','The National FINRISK Study',9606),
	('PRJEB7898','The Eli and Edythe L. Broad Institute of Harvard and MIT','The Exome Aggregation Consortium (ExAC) is a coalition of investigators seeking to aggregate and harmonize exome sequencing data from a variety of large-scale sequencing projects, and to make summary data available for the wider scientific community.',NULL,'Germline','Aggregate','The Exome Aggregation Consortium (ExAC) v0.2',9606),
	('PRJEB7923','University of California Los Angeles','The Vervet Genetic Mapping Project (VGMP) devloped genomic tools and resources for genetic trait maping in vervet monkey (AKA African green monkey). This project generated genome-wide SNP panels dedicated specifically for genetic mapping in Caribbean-origin sabaeus vervets (Chlorocebus aethiops sabaeus). The Assocation Mapping Panel comprises of ~500K SNPs (r2=0.9). The Linkage Mapping Panel comprises of ~150K SNPs (r2=0.5).',NULL,'Germline','Control Set','Vervet Genetic Mapping Project',60711),
	('PRJEB8636','deCODE Genetics','Autosomal sequence variants identified in deCODE\'s whole-genome sequencing of 2,636 Icelanders',NULL,'Germline','Control Set','deCODE Genetics Whole-Genome Sequencing Variants',9606),
	('PRJEB8639','Technical University of Denmark; Aarhus University; Copenhagen University; BGI-Europe','This is an aggregate vcf of SoapAsmVar Indels calls (10nt-50nt) from 10 trios sequenced to high depth from the first phase Danish Pangenome project',NULL,'Germline','Control Set','GenomeDK Release 1 SoapAsmVar-Indels calls',9606),
	('PRJEB8650','Technical University of Denmark; Aarhus University; Copenhagen University; BGI-Europe','This is an aggregate vcf of GATK SNV calls from 10 trios sequenced to high depth from the first phase Danish Pangenome project',NULL,'Germline','Control Set','GenomeDK Release 1 SNV calls',9606),
	('PRJEB8652','Technical University of Denmark; Aarhus University; Copenhagen University; BGI-Europe','This is an aggregate vcf of GATK Indels calls from 10 trios sequenced to high depth from the first phase Danish Pangenome project',NULL,'Germline','Control Set','GenomeDK Release 1 GATK-Indels calls',9606),
	('PRJEB8661','The Eli and Edythe L. Broad Institute of Harvard and MIT','The Exome Aggregation Consortium (ExAC) is a coalition of investigators seeking to aggregate and harmonize exome sequencing data from a variety of large-scale sequencing projects, and to make summary data available for the wider scientific community.',NULL,'Germline','Control Set','The Exome Aggregation Consortium (ExAC) v0.3',9606),
	('PRJEB9373','Department of Ecology and Evolutionary Biology, Yale University, New Haven, Connecticut 06511, USA','Genotyping of multiple Aedes aegypti mosquito populations worldwide using a novel SNP chip.',NULL,'Germline','Control Set','A multipurpose high throughput SNP chip for the dengue and yellow fever mosquito, Aedes aegypti',7159),
	('PRJEB9507','Fisheries and Forestry Queensland','These data report 8 M high-quality SNPs, 1.9 M indels and specific gene loss and gain events in S. bicolor.',NULL,'Germline','Control Set','Whole-genome Sequencing Reveals Untapped Genetic Potential in Sorghum',4557),
	('PRJEB9586','HARVARD MEDICAL SCHOOL, DEPARTMENT OF GENETICS','The most powerful way to study population history and natural selection is to analyze whole genome sequences, which contain all the variation that exists in each individual. To date, genome-wide studies of history and selection have primarily analyzed data from single nucleotide polymorphism (SNP) arrays which are biased by the choice of which SNPs to include. Alternatively they have analyzed sequence data that have been generated as part of medical genetic studies from populations with large census sizes, and thus do not capture the full scope of human genetic variation. Here we supply high quality genome sequences (~40x average) from 301 individuals from 146 worldwide populations. All samples were sequenced using an identical protocol at the same facility (Illumina Ltd.). We modified standard pipelines to eliminate biases that might confound population genetic studies, to produce a unique alignment and genotype dataset.',NULL,'Germline','Control Set','Deep genome sequencing for diverse human populations from around the world',9606),
	('PRJEB9656','Federal State Budgetary Institution «Research Centre For Medical Genetics», Moscow, Russia','Chronic myeloid leukemia can be well controlled by targeted tyrosine kinase inhibitors (TKI). In some patients it is possible to terminate expensive and toxic long-life therapy, however about 50% of these patients relapse without treatment. There are also about 10% of patients with primary resistance or low efficacy of the therapy. In our study we found promising new potential early prognostic markers and molecular targets for developing new drugs.',NULL,'Germline','Case Control','Prognostic factors of early response to TKI and remission stability in chronic myeloid leukemia by whole exome sequencing',9606),
	('PRJEB9799','UNIVERSITY OF FLORIDA','Completed in 2009, the reference genome assembly of the domesticated horse (EquCab 2.0) produced the majority of publically available annotations of genetic variations in this species.  Following that effort, a few other projects that focused at variant discovery of a particular breed or two. In this project we aim to identify and annotate single nucleotide polymorphisms (SNPs), insertions and deletions (INDELs), copy number variations (CNVs) and structural variations (SVs) in the genomes six horses of diverse genetic background using next generation sequencing.',NULL,'Germline','Control Set','Whole genome detection of sequences of six horses from diverse breeds.',9796),
	('PRJEB9822','Wellcome Trust Sanger Institute','Population genetics study of 138 samples looking for genetic evidence of an origin of the Armenians from Bronze Age mixing of multiple populations',NULL,'Germline','Control Set','Genetic evidence for an origin of the Armenians from Bronze Age mixing of multiple populations',9606),
	('PRJEB9857','Federal State Budgetary Institution «Research Centre For Medical Genetics», Moscow, Russia','Chronic myeloid leukemia can be well controlled by targeted tyrosine kinase inhibitors (TKI). However there is about 10% of patients with primary resistance or low efficacy of the therapy. In our study we found promissing new potential early prognostic markers and molecular targets for developing new drugs.  ',NULL,'Germline','Case Control','Prognostic factors of early response to TKI in chronic myeloid leukemia by whole exome sequencing',9606),
	('PRJEB9858','Federal State Budgetary Institution «Research Centre For Medical Genetics», Moscow, Russia','Chronic myeloid leukemia can be well controlled by targeted tyrosine kinase inhibitors (TKI). In some patients it is possible to terminate expensive and toxic long-life therapy, however about 50% of these patients relapse without treatment. In our study we found promissing new potential early prognostic markers and molecular targets for developing new drugs.',NULL,'Germline','Case Control','Prognostic factors of stable remission after cessation of TKI therapy in chronic myeloid leukemia by whole exome sequencing',9606),
	('PRJNA273563','The 1001 Genomes Project Consortium','1001 Genomes: A Catalog of Arabidopsis thaliana Genetic Variation',NULL,'Germline','Control Set','1001 Genomes: A Catalog of Arabidopsis thaliana Genetic Variation',3702),
	('PRJNA289433','BGI-Shenzhen','Study of Major Depression in Chinese women',NULL,'Germline','Control Set','Study of Major Depression in Chinese women',9606),
	('PRJX00001','National Center for Biotechnology Information (NCBI)','This project contains the human variant data from dbSNP build 144.',NULL,'Germline','Aggregate','Human Variation Data From dbSNP build 144',9606);

/*!40000 ALTER TABLE `projects` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table taxonomies
# ------------------------------------------------------------

DROP TABLE IF EXISTS `taxonomies`;

CREATE TABLE `taxonomies` (
  `taxonomy_id` int(11) NOT NULL,
  `taxonomy_common_name` varchar(255) DEFAULT NULL,
  `taxonomy_scientific_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`taxonomy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `taxonomies` WRITE;
/*!40000 ALTER TABLE `taxonomies` DISABLE KEYS */;

INSERT INTO `taxonomies` (`taxonomy_id`, `taxonomy_common_name`, `taxonomy_scientific_name`)
VALUES
	(3702,'Thale cress','Arabidopsis thaliana'),
	(3885,'Common bean','Phaseolus vulgaris'),
	(4081,'Tomato','Solanum lycopersicum'),
	(4530,'Rice','Oryza sativa'),
	(4557,'Sorghum','Sorghum'),
	(4577,'Maize','Zea mays'),
	(4896,'Fission yeast','Schizosaccharomyces pombe'),
	(6183,'Blood fluke','Schistosoma mansoni'),
	(7159,'Mosquito','Aedes aegypti'),
	(7165,'Mosquito','Anopheles gambiae'),
	(7173,'Mosquito','Anopheles arabiensis'),
	(7955,'Zebrafish','Danio rerio'),
	(9606,'Human','Homo sapiens'),
	(9796,'Horse','Equus caballus'),
	(9823,'Pig','Sus scrofa'),
	(9913,'Cow','Bos taurus'),
	(9923,'Goat','Capra aegagrus'),
	(9925,'Goat','Capra hircus'),
	(9935,'Sheep','Ovis'),
	(9938,'Sheep','Ovis aries musimon'),
	(9940,'Sheep','Ovis aries'),
	(10088,'Mouse','Mus'),
	(10116,'Rat','Rattus norvegicus'),
	(30066,'Mosquito','Anopheles merus'),
	(30069,'Mosquito','Anopheles stephensi'),
	(30523,'Cow','Bos taurus x Bos indicus'),
	(34506,'Rat threadworm','Strongyloides ratti'),
	(34690,'Mosquito','Anopheles melas'),
	(34691,'Mosquito','Anopheles quadriannulatus'),
	(39947,'Rice','Oryza sativa Japonica Group'),
	(59896,'Sheep','Ovis vignei'),
	(60711,'Vervet monkey','Chlorocebus sabaeus'),
	(62324,'Mosquito','Anopheles funestus'),
	(69004,'Mosquito','Anopheles farauti'),
	(74873,'Mosquito','Anopheles sinensis'),
	(112268,'Mosquito','Anopheles minimus'),
	(112509,'Barley','Hordeum vulgare subsp. vulgare'),
	(139723,'Mosquito','Anopheles culicifacies'),
	(199890,'Mosquito','Anopheles epiroticus'),
	(215358,'Large yellow croaker','Larimichthys crocea'),
	(469796,'Sheep','Ovis orientalis');

/*!40000 ALTER TABLE `taxonomies` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
